#+Title: How Recovery Password in Router
#+Author: Mohammed K Alnahdi
#+Date: 11th Feb 2022

* Introduction
  The reason for founding recovery password is losing password or forgeting from the technical that setup router.
  and this we will describe how recovery password.

*** Step One: Plug the Compuer
  You must plug computer in the router via Console cable.
*** Step Two: Restart Router.
  For this step, we unplug the router from electricity and re-plug to make restart.
  While restart and boot the system type Ctrl + C for stoping the loading the system.
*** Step Three: Change Register for System:
  After do *Step Two* we will go to *Rommon* Mode and we must change number or Register by adding:

  Router > confreg 0x2142
  Router > reset

*** Step Four: Save startup in NVRAM
  After do the *Step Three* you will go to other register, So copy setup to NVRAM to reset.

  Router> enable
  Router# copy startup-config running-config

*** Step Five: Finalization
  Now after copy the setup in NVRAM we should disable all password by these commands:

  Router# show running-config                    ;; show setup in the router.
  Router# config terminal
  Router(config)# no enable secret               ;; this for disable password privilege
  Router(config)# line console 0                 ;; to enter to Aux port
  Router(config-line)# no password               ;; this for disable password for AUX
  Router(config-line)# exit                      ;; to exit of port AUX
  Router(config)# no service password-encryption ;; for disable encryption.
  Router(config)# config-register 0x2102         ;; *important* we must return to old register
  Router(config)# end                            ;; to exit config mode.
  Router# Copy running-config startup-config     ;; save setup again.
