#+Title: How set Router Password
#+Author: Mohammed K Alnahdi
#+date: 11th Feb 2022

* Introduction:
Before start to secure router, we must remember about ports include the router.

** Set Password in port AUX
   /AUX/ is port to modifing setting by remote control.
*** Step One: Plug the computer to router.
   There is tow ways to plug device into router:
   - Plug computer into router via *Console Port*:
     Plug in Console Port is important to enter to setup and it is primery port for that. but it is imparctical method if the router is far or hard to plug it.
   - Enter into router via Telnet by any computer in network:
     This way will explain later.

*** Step Two: Enter command:
   Router> enable
   Router# config terminal
   Router(config)# line aux 0                 ;;zero is number of port for setup
   Router(config-line)# password abc123       ;;abc123 is password
   Router(config-line)# login                 ;;the password for login to setup

** Set Password in Telnet
   /vty/ is port that allow telent to client computer for accessing router.
*** Step One: Plug the computer by network
    We must link the device in the same network.
*** Step Two: Enter commands:
    Router> enable
    Router# config terminal
    Router(config)# line vty 0
    Router(config-line)# password abc123      ;; abc123 is password
    Router(config-line)# login
    
** Set Password for Privilege:
   /Privilege/ is super mode that executed by *enable* command.
*** Step One: Plug the computer to router.
    this step remind in *Set Password in port AUX*.
*** Step Two: Enter commands:
     Router>enable
     Router# config terminal
     Router(config)# enable password abc123    ;;abc123 is password

** Set Password Encryption AUX:
    The Password will appeare if someone query the setup by using command *show running-config*.
*** Step One: Plug the computer to router.
    this step remind in *Set Password in port AUX*.
*** Step Two: Enter commands:
    Router>enable
    Router# config terminal
    Router(config)# service password-encryption

** Set Password Encryption Privilege mode:
    The Password will appeare if someone query the setup by using command *show running-config*.
*** Step One: Plug the computer to router.
    this step remind in *Set Password in port AUX*.
*** Step Two: Enter commands:
    Router>enable
    Router# config terminal
    Router(config)# enable secret abc123    ;;abc123 is privilege password.
    
